export const Colors = {
  primaryBold: "#70369D",
  primaryLight: "#b197fc",
  primaryBackground: "#d0bfff",
  primaryBackgroundLight: "#F8F0FC",
  primaryGrey: "#C3B6D7",
  greyLight: "#DAD6DE",
  error100: "#fcdcbf",
  error500: "#f37c13",
  primaryText: "#434955",
  primarySmoking: "#D0EBFF",
  primaryExercise: "#d0bfff",
  primaryAlcohol: "#FFC9C9",
  primaryDiet: "#D8F5A2",
};
